### PR TITLE
Python versions tested now 2.7-3.6

### PR DESCRIPTION
**Pull request by davidread**
* Test support for python up to 3.6.
* Not going to python 3.7, due to weird test failure - for someone to tackle in another PR
* Drop testing for python 2.6, since 2 is going soon anyway.

### CODE REVIEW

**Comment by davidread** [comment]
Curious error with python 3.7 only - maybe xlrd is not compatible?
```
======================================================================
FAIL: test_attempt_read_encrypted_no_password_xls (test.test_read.ReadXlsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/okfn/messytables/messytables/excel.py", line 47, in get_workbook
    formatting_info=with_formatting_info)
xlrd.biffh.XLRDError: Workbook is encrypted
```

**Comment by davidread** [comment]
@StevenMaude could you review/merge please?

**Comment by davidread** [comment]
@pudo perhaps you could review/merge this please?

**Comment by StevenMaude** [comment]
NB: I don't have write access to this repo any longer to merge, but looks fine to me if the tests pass.

**Pull request merged**
