### PR TITLE
127 newer ODS compatibility

### PR DESCRIPTION
**Pull request by davidread**
Issue: https://github.com/okfn/messytables/issues/127

### CODE REVIEW

**Comment by davidread** [comment]
@rossjones @drj11 ready for review now, if you have a chance

**Comment by davidread** [comment]
rufus said it was ok to merge my own PR

**Comment by drj11** [comment]
@davdidread FWIW, I did have a look earlier, but didn't spend enough time on it to merge it. I appreciate the ping, and have no problems with you merging it yourself when we're not responsive.

**Comment by davidread** [comment]
@drj11 No worries, thanks

**Pull request merged**
