### PR TITLE
Consolidated changes: typecast, python 3 support, etc.

### LINKED ISSUE #154: Boolean type parses values 0 and 1 backwards
This code https://github.com/okfn/messytables/blob/master/messytables/types.py#L117 considers "0" to be True, and "1" to be False. That seems the opposite of what it should do.

### PR DESCRIPTION
**Pull request by pudo**
This changeset supersedes #139, and includes a variety of changes to improve Python 3 support (using `six` directly).

I expect this to fix #154, #146, #50, #40, #117 and make #37, #140, #148, #149 into issues for typecast.

### CODE REVIEW

**Comment by pudo** [comment]
Ok, this is pretty weird: I'm seeing a lot of errors popping up for Python 3 on Travis that aren't there on my local machine. It seems that there's some mismatch that I can't quite put my finger on, plus probably some incompatibilities I introduced with the simplified CSV parser. Would really appreciate any advice, @pwalsh!

**Comment by pwalsh** [comment]
@pudo ok i'll check it soon. Our CSV (and more) parser at https://github.com/frictionlessdata/tabulator-py should be well and truly on top of Py2/3 issues, FYI :).

**Comment by pudo** [comment]
Interesting. Should we be using that/proxying that? It looks from a first glance like we'd need to add encoding detection etc. -- which is exactly where the weird Py2/3 impedance comes in: https://github.com/frictionlessdata/tabulator-py/blob/master/tabulator/parsers/csv.py#L57

**Comment by pwalsh** [comment]
@pudo https://github.com/frictionlessdata/tabulator-py/blob/master/tabulator/helpers.py#L55

**Comment by StevenMaude** [comment]
@pudo Rebased your branch on master as a [new branch](https://github.com/okfn/messytables/tree/cleanup-mt2-redux), and managed to get [Travis to pass on Python 2.7, 3.4 and 3.5](https://travis-ci.org/okfn/messytables/builds/165062835). :tada:

It was mostly already there apart from one or two things I changed.

Be nice for me to test it with xypath/databaker; will try take a look at that this week. Would be great to get it merged though as it closes off several issues :+1

**Comment by pudo** [comment]
@StevenMaude wow, that's brilliant. One thing I'd really still like to do before a release is to invert the file type detection, i.e. make [file type associations](https://github.com/okfn/messytables/blob/master/messytables/any.py#L7) properties of the ``TableSet`` classes, rather than in ``any.py``. Once that's done, I think it'd be fair to call this MT2.

**Comment by davidread** [comment]
Closed in favour of #171

**Pull request closed without merging**
