### PR TITLE
151 rename types.py

### PR DESCRIPTION
**Pull request by mcarans**
Rename types.py to messytypes.py to prevent file name clash on sys.path which gives error: AttributeError: 'module' object has no attribute 'ClassType'

### CODE REVIEW

**Comment by pwalsh** [comment]
@mcarans when did you encounter this error? I know the nature of the problem of course, but seeing as this codebase has several years under its belt, I'm reluctant to accept this (breaking) change.

@pudo WDYT?

**Comment by pudo** [comment]
Strongly feel that this is indicative of a messed up Python environment, and that we shouldn't accept this.

**Comment by pwalsh** [comment]
@mcarans closing this. thanks anyway.

**Comment by mcarans** [comment]
Ok thx. I haven't used messytables for some time now. If I come across the problem again, I'll let you know.

**Pull request closed without merging**
