### PR TITLE
Add comments about purpose of atof and atoi

### PR DESCRIPTION
**Pull request by davidread**
Also:
* Get rid of bare exceptions
* PEP8
* Fix copyright year, OKI name and mention outside contributors

### CODE REVIEW

**Comment by davidread** [comment]
@pwalsh this PR has been hanging around - is there someone who could quickly review and merge this?

**Comment by davidread** [comment]
Or @StevenMaude can you merge since you're the maintainer afaict?

**Comment by pwalsh** [comment]
@davidread yes, we agreed to have @pudo take over again as active maintainer of this library. I can do it but let's check with him first. Also, the license change for Open Knowledge is wrong, as the legal entity is still "The Open Knowledge Foundation Ltd."

**Comment by davidread** [comment]
Ok thanks @pwalsh I've fixed that name. Please do provide a review and that will help @pudo.

**Comment by StevenMaude** [comment]
Also LGTM, for what it's worth.

**Pull request merged**
